---
title: "Populism at Home"
author: "Margaret Tate"
description: "An investigation into right wing populist rhetoric in US battleground states"
output:
  html_document:
    theme:
      version: 5
      base_font: {google: "Roboto"}
      heading_font: {google: "Playfair Display"}
      code_font: {google: "JetBrains Mono"}

  distill::distill_article:
    self_contained: false
---

## Background 

The research done for the paper this data set was originally collected for was the first attempt at quantitative measures of populist ideas among US state level officials. The data set, called the *US Governors Populism Database*, in an extension of the *Global Populism Database*, and uses the same holistic grading of speech samples, measurement technique, and analogous sampling. The research included analysis of 400 speeches from 100 governors across all 50 states. The sample included two governor terms for each state, one before and one after the 2016 election. The research was initially done with the goal of collecting and analyzing quantitative evidence of populist rhetoric among sub national party officials to test claims by scholars that Trump's election 2016, and again in 2024, was part of a greater wave of radical right populism across Western Democracies.

The study found that in the US, the election of a populist national leader, Donald Trump, was not necessarily associated with high levels of sub national populism. While Republican governors show higher levels of populist rhetoric than Democrats, this difference predates Trump’s presidency and showed no evidence of intensifying following his first election. 

I am interested in how these conclusions about right wing populism in sub national leaders changes when you consider if a state is a swing state: a state where constituents are significantly divided down party lines and experience high-intensity campaigning during election cycles. In 2016, Trump won a signifciant  majority of key US swing states, effectively "flipping the blue wall" including Pennsylvania, Michigan, Wisconsin, Florida, Ohio, Iowa, North Carolina, and Arizona.   

# Hypothesis 

In battleground states, elections are intensely competitive and outcomes are uncertain, as neither major party has a consistent lock on the majority vote. These states are characterized by political diversity, rapidly shifting demographics, high sensitivity to economics, and intense campaign focus. 

Right wing party members, the party of interest for this analysis, cannot rely on conservative bases to win and need to persuade independents, low-information voters, and dissected democrats in order to win in these states. Additionally, populist rhetoric, which is "anti-establishment," "us vs. them," and offers simplistic solutions with emotional appeal, appeals across party lines and activates voters who feel left behind economically, which would make it effective in battleground states. This leads me to believe that in an environment of intense campaigning and competition, sub national conservatives in swing states may have adapted their rhetoric to be more populist. I don't believe this would have happened in solid "red" states because these leaders can rely of traditional conservative messaging with their ideologically aligned conservative bases, less competition, and less need to mobilize swing voters. 

Additionally, I believe this logic will hold both during and after Trump's victory as sub national leaders in swing states would have observed the success of Trump style populism in swing states and attempt to use it at sub national levels. 


During and after the 2016 campaign cycle and election, if a state was characterized as being a "swing state" or "battleground state", populist rhetoric among their republican sub national leaders will be higher then among sub national leaders in "red" states with conservative strongholds.   

## Data 

```{r, intial data section, echo = FALSE}
library(tidyverse)
gov_populism <- read.csv("replication_data.csv") 
rep_data <- gov_populism |>
  filter(party == "R") |>
  mutate(swing = if_else(state %in% c("Florida1", "Florida2",
                       "Ohio1", "Ohio2",
                       "Pennsylvania1", "Pennsylvania2",
                       "Michigan1", "Michigan2",
                       "Wisconsin1", "Wisconsin2",
                       "North Carolina1", "North Carolina2",
                       "Iowa1", "Iowa2", 
                       "Nevada1", "Nevada2",
                       "Colorado1", "Colorado2", "New Hampshire1", "New Hampshire2", "Virginia1", "Virginia2"), "Swing State", "Not Swing State")) 
  boxplot_fig1 <-ggplot(rep_data, aes(x = swing, y = score)) +
    geom_boxplot() +
    labs(title = "Populism Scores of Conservative Governers: Swing vs. Red States", x = "State Type", y = "Populism Score", caption = "Figure 1")
boxplot_fig1

```








